name: sultanpos
description: Sultan POS 2.0
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.1.0
  bitsdojo_window: ^0.1.2
  blurrycontainer: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  http_mock_adapter: ^0.3.3
  intl: ^0.18.1
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  json_annotation: ^4.6.0
  jwt_decode: ^0.3.1
  lehttp_overrides: ^1.0.2
  motion_toast: ^2.3.3
  nanoid: ^1.0.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  reactive_forms: ^14.1.0
  shared_preferences: ^2.0.15
  syncfusion_flutter_datagrid: ^21.2.4
  test: ^1.21.4

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.2
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - resources/images/icon_1024.png
  fonts:
    - family: Oxanium
      fonts:
        - asset: resources/fonts/Oxanium/Oxanium-Bold.ttf
        - asset: resources/fonts/Oxanium/Oxanium-ExtraBold.ttf
        - asset: resources/fonts/Oxanium/Oxanium-ExtraLight.ttf
        - asset: resources/fonts/Oxanium/Oxanium-Light.ttf
        - asset: resources/fonts/Oxanium/Oxanium-Medium.ttf
        - asset: resources/fonts/Oxanium/Oxanium-Regular.ttf
        - asset: resources/fonts/Oxanium/Oxanium-SemiBold.ttf
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
analizer:
  errors:
    invalid_annotation_target: ignore
