name: sultanpos
description: Sultan POS 2.0
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.1.0
  bitsdojo_window: ^0.1.2
  blurrycontainer: ^2.1.0
  dio: ^5.5.0+1
  dropdown_button2: ^2.1.3
  flutter:
    sdk: flutter
  flutter_esc_pos_utils: ^1.0.1
  flutter_pos_printer_platform_image_3: ^1.2.0
  font_awesome_flutter: ^10.4.0
  http_mock_adapter: ^0.6.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  jwt_decode: ^0.3.1
  lehttp_overrides: ^1.0.2
  nanoid: ^1.0.0
  oktoast: ^3.3.1
  path: ^1.8.3
  path_provider: ^2.1.4
  protobuf: ^3.0.0
  provider: ^6.1.2
  reactive_forms: ^17.0.1
  scaled_app: ^2.3.0
  shared_preferences: ^2.3.1
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.24
  syncfusion_flutter_datagrid: ^22.1.34
  test: ^1.21.4
  tinycolor2: ^3.0.1
  ulid: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - resources/images/icon_1024.png
    - resources/images/old_icon_512.png
  fonts:
    - family: Ubuntu
      fonts:
        - asset: resources/fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: resources/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
        - asset: resources/fonts/Ubuntu/Ubuntu-Italic.ttf
        - asset: resources/fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: resources/fonts/Ubuntu/Ubuntu-LightItalic.ttf
        - asset: resources/fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: resources/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
        - asset: resources/fonts/Ubuntu/Ubuntu-Regular.ttf
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
analizer:
  errors:
    invalid_annotation_target: ignore
